[project]
name = "cnpj-xray"
version = "0.1.0"
description = "CNPJ-XRay - ETL e análise dos dados públicos de CNPJ da Receita Federal do Brasil"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "httpx>=0.27.0",
    "beautifulsoup4>=4.12.0",
    "lxml>=5.0.0",
    "firebird-driver>=2.0.0",
    "python-dotenv>=1.0.0",
    "pathlib",
    "tenacity>=8.0.0",
    "rich>=13.0.0",
    "polars>=1.42.1",
]
